name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [course-service, user-service, progress-service, apache-proxy]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }} ./${{ matrix.service }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}
